### ISSUE TITLE
Lv.5 과제 피드백 - 작성자: 류제천 튜터

### ISSUE THREAD

**Issue by rjc1704** [HyunseoY/bamboo-community#1]
# Overview
- 리드미 작성 잘해주셨습니다.
- API Table에서 GET Method의 경우, request 는 비워주시고, url에 params를 추가해야 하는경우, URL에 "/detail/:id" 이런 방식으로 표기해 주시면 좋습니다.
- 로그인/회원가입 폼 유효성검사 로직이 없습니다. 아이디와 비밀번호가 모두 입력되지 않으면, API 요청을 보내지 않도록 해야 합니다. (지금은 보냅니다.)
- 로그인을 하지 않았을 경우, 웹페이지에 들어가지 못하도록 해야합니다. 사용자가 url 조작을 통하거나 로그아웃 후에 뒤로 가기 눌렀을 때 여전히 메인 페이지로 접근이 가능합니다.
- 로그인을 한 경우에는 로그인 페이지에 접근할 수 없어야 합니다. 지금은 가능합니다.
- 로그아웃 할 때 "로그아웃 되었습니다" 에 confirm을 붙이는 것은 다소 어색하게 느껴집니다. confirm 을 할 때는 의문형으로 "로그아웃 하시겠습니까?"가 더 적절해 보이고, 로그아웃 처리는 작성중인 form이 있는게 아닌 이상 confirm 없이 바로 처리해도 괜찮습니다.
- authorizationUser 를  로그인/회원가입 페이지 외의 사용자에 의한 서버 요청 마다 실행시켜서 jwt로 인가요청을 보내야 합니다. 그래야 jwt 토큰이 만료되었을 때의 응답을 받았을 때 로그아웃 처리 및 로그인페이지로 redirect 처리를 제대로 할 수 있습니다.

코드 레벨의 피드백은 아래에 드리겠습니다.

**Comment by rjc1704** [comment]
https://github.com/HyunseoY/bamboo-community/blob/04d7ad152627826102be4a217150d66306f638b1/src/api/user.js#L41-L53

위 코드가 웹서비스 내에서 CRUD 하기 전마다 실행되도록 해줘야 합니다. 그리고 status 값이 200이면 정상적으로 서비스를 진행하고, 400번대의 statusCode를 받으면 로그아웃 처리 후 로그인페이지로 강제로 페이지이동 처리(redirect) 시켜주시면 됩니다.

**Comment by rjc1704** [comment]
https://github.com/HyunseoY/bamboo-community/blob/04d7ad152627826102be4a217150d66306f638b1/src/pages/Login.jsx#L18-L38

try 문 전에 20번 줄에서 id와 password에 대한 유효성검사가 먼저 이뤄지고 유효성검사 통과 못할 시 alert나 알림문구를 화면에 보여주고 return 으로 함수를 중간에 끝내는 로직이 필요합니다.

**Comment by HyunseoY** [comment]
감사합니다!!
